---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart kiosk
  ansible.builtin.systemd:
    name: kiosk.service
    state: restarted
  when: kiosk_start_compositor

- name: Restart triggerhappy
  ansible.builtin.systemd:
    name: triggerhappy.service
    state: restarted
